using Pkg
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("Dates")
Pkg.add("Statistics")
Pkg.add("Plots")
Pkg.add("MLJ")
Pkg.add("Random")
Pkg.add("ScikitLearn")
Pkg.add("GLM")
Pkg.add("HTTP")
Pkg.add("CodecZlib")
Pkg.add("Tables")
# Pkg.add("Mongoc")
Pkg.add("VaderSentiment")
Pkg.add("PyCall")
Pkg.add("StatsBase")
Pkg.add("DataFramesMeta")
Pkg.add("GR")